### ISSUE TITLE
[Q] Big-endian support

### ISSUE THREAD

**Issue by WojciechMigda** [pguyot/arm-runner-action#46]
Hi, is it possible to set-up the runner in big-endian mode?

**Comment by pguyot** [comment]
Do you have an image in big endian? If you do, it should be pretty easy a feature to add.

**Comment by WojciechMigda** [comment]
I am afraid I am not aware of existence of such image.

**Comment by pguyot** [comment]
Closing this issue then, feel free to reopen if a use case / big endian image pops up. NetBSD has a Big Endian image but we need a linux one to run binaries using qemu-user.
