### ISSUE TITLE
Increase disk space in image?

### ISSUE THREAD

**Issue by YPares** [pguyot/arm-runner-action#67]
Hello! Is there a way to increase available disk space in the image? I'm trying to build a project with a few dependencies ( https://github.com/YPares/arpligner/actions/runs/4083649809/jobs/7039425655 ) and fail because of /var/cache/apt/archives/ not having enough space, though my Ubuntu x64 build job (which installs about the same dependencies) works fine.

**Comment by pguyot** [comment]
It is definitely possible with option `image_additional_mb`.

**Comment by YPares** [comment]
@pguyot Damn I missed that one ^^. Sorry about that and thanks!
