### ISSUE TITLE
Apple silicon ?

### ISSUE THREAD

**Issue by danielbraun89** [pguyot/arm-runner-action#72]
More of a question than an issue,  can this action can be modified/altered in a way that will allow compiling into Apple silicon ARM architecture (M1/2  cpus etc)?

**Comment by pguyot** [comment]
Interesting prospect. This action uses user mode qemu emulation and qemu does not support this on macOS. It would require this as well as macOS ARM libraries to link with.

See: https://www.qemu.org/docs/master/user/index.html
