### ISSUE TITLE
Maven fails to launch

### ISSUE THREAD

**Issue by dev-sda1** [pguyot/arm-runner-action#81]
Hi,

I'm working on experimenting with some automation with this action to build Maven projects designed for the Raspberry Pi, however attempting to run maven returns ``java.lang.ClassNotFoundException: org.apache.maven.cli.MavenCli`` if I try to run any maven command, whether that's ``mvn -v``, ``mvn package``, etc.

I've tried using maven from source and apt but both result in the same error. Running Bellsoft JDK 17.

I've attached the full runner logs in a [gist here](https://gist.github.com/dev-sda1/900f1b65d20eb12e74733d382fbc06ae)
YML file: https://gist.github.com/dev-sda1/886932435d773670c30647bbf14d5bd6

**Comment by pguyot** [comment]
I'd say it's a problem with the jdk you are installing.
It works with `default-jdk` apt package.

```
      - uses: pguyot/arm-runner-action@v2.5.2
        with:
          cpu_info: cpuinfo/raspberrypi_4b
          base_image: raspios_lite_arm64:latest
          bind_mount_repository: true
          cpu: cortex-a53
          image_additional_mb: 12000
          optimize_image: false
          copy_repository_path: /opt/project
          commands: |
            # Disable IPv6 in case it is configured but does not work
            ping6 -c 1 www.ietf.org || sudo sysctl -w net.ipv6.conf.eth0.disable_ipv6=1
              
            sudo apt-get update -y --allow-releaseinfo-change
            sudo apt install -y default-jdk
            wget https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz
            tar -xvf apache-maven-3.9.4-bin.tar.gz
            sudo mv apache-maven-3.9.4 /opt/
            export PATH="/opt/apache-maven-3.9.4/bin:$PATH"
            echo $(mvn -v)
```
