### ISSUE TITLE
Build in Docker on self-hosted agent.

### ISSUE THREAD

**Issue by pompushko** [pguyot/arm-runner-action#96]
Hello

Is there any possibilities to build on self-hosted agent in Docker? I can build without Docker on ubuntu-latest cloud github agent and on mine self-hosted.

Thank you.

**Comment by pompushko** [comment]
Seems like this is an issue https://github.com/actions/runner/issues/716

```
cc1: fatal error: /home/user/actions-runner/_work/_actions/pguyot/arm-runner-action/v2/qemu-wrapper.c: No such file or directory
```

**Comment by pompushko** [comment]
@pguyot  hello :)

Could you please check my issue?
Thank you!

**Comment by pguyot** [comment]
Could you please try #102 and let me know if it works for you?

**Comment by pompushko** [comment]
> Could you please try #102 and let me know if it works for you?

Sure! Thank you, this evening :)
